### ISSUE TITLE
Clear Old Data from Autonomous DB

### ISSUE THREAD

**Issue by asifsharafudeen90** [adizohar/usage_reports_to_adw#1]
Hi , 
From the day one of our  Oracle Cloud journey we onboarded  USAGE ADW solution to get insights about our usage and cost. 
Almost a year now we could see autonomous database is full with 20 GB data because we are using the free tier, is there a way to clear the old data like only keep last 6 months data. 
Can you provide some scripts or command to run and clear the old data.

**Comment by adizohar** [comment]
Hi, I would suggest to truncate the tables and load again start from last 6 months
First update the $HOME/usage_reports_to_adw/config.user EXTRACT_DATE=2022-01
Then run truncate the tables:
https://github.com/adizohar/usage_reports_to_adw/blob/main/setup/truncate_tables.sql
The crontab will start loading again from 2022-01
