### ISSUE TITLE
git clone is failing with bash: line 84: git: command not found

### ISSUE THREAD

**Issue by vipasi** [adizohar/usage_reports_to_adw#3]
########################################################################
# 4. Clone OCI Python SDK Git.
########################################################################
bash: line 84: git: command not found
chmod: cannot access '/home/opc/usage_reports_to_adw/setup/*.sh': No such file or directory
chmod: cannot access '/home/opc/usage_reports_to_adw/shell_scripts/*.sh': No such file or directory
Completed.
##################################################
# End process at Thu Feb 23 04:57:38 GMT 2023
##################################################
[opc@usagevm ~]$ /home/opc/usage_reports_to_adw/setup/setup_credentials.sh
-bash: /home/opc/usage_reports_to_adw/setup/setup_credentials.sh: No such file or directory

**Comment by adizohar** [comment]
HI, I was missing the below in the setup_packages.ol8.sh:
sudo yum -y install git
I added it, you can try again
